# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every month
    schedule:
      interval: 'monthly'
    versioning-strategy: increase
    # Limit the number of open pull requests for node dependencies
    open-pull-requests-limit: 25
    # group related packages into one PR
    # dependabot doesn't support YAML aliases so this is copied-and-pasted for all npm ecosystems https://github.com/dependabot/dependabot-core/issues/1582
    groups:
      react-stack:
        patterns:
          - react
          - react-dom
          - next
          - "@next/*"
          - "@mdx-js/*"
      mui-stack:
        patterns:
          - "@mui/*"
          - "@emotion/*"
          - styled-components
      eslint-stack:
        patterns:
          - eslint
          - eslint-*
          - "@eslint/*"
          - "@typescript-eslint/*"
      typescript-stack:
        patterns:
          - typescript
          - ts-node
          - "vite-tsconfig-paths"
      testing-stack:
        patterns:
          - vitest
          - "@vitest/*"
          - "@testing-library/*"
          - cypress
          - supertest
          - jsdom
      aws-sdk-stack:
        patterns:
          - "@aws-sdk/*"
          - "@smithy/*"
      rjsf-stack:
        patterns:
          - "@rjsf/*"
      opentelemetry-stack:
        patterns:
          - "@opentelemetry/*"
          - "@vercel/otel"
      formatting-stack:
        patterns:
          - prettier
          - eslint-plugin-prettier
      markdown-stack:
        patterns:
          - markdown-*
          - remark-*
          - rehype-*
          - "@uiw/react-markdown-preview"
          - "@uiw/react-md-editor"

  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `/frontend` directory
    directory: '/frontend'
    schedule:
      interval: 'monthly'
    versioning-strategy: increase
    open-pull-requests-limit: 25
    # dependabot doesn't support YAML aliases so this is copied-and-pasted for all npm ecosystems https://github.com/dependabot/dependabot-core/issues/1582
    groups:
      react-stack:
        patterns:
          - react
          - react-dom
          - next
          - "@next/*"
          - "@mdx-js/*"
      mui-stack:
        patterns:
          - "@mui/*"
          - "@emotion/*"
          - styled-components
      eslint-stack:
        patterns:
          - eslint
          - eslint-*
          - "@eslint/*"
          - "@typescript-eslint/*"
      typescript-stack:
        patterns:
          - typescript
          - ts-node
          - "vite-tsconfig-paths"
      testing-stack:
        patterns:
          - vitest
          - "@vitest/*"
          - "@testing-library/*"
          - cypress
          - supertest
          - jsdom
      aws-sdk-stack:
        patterns:
          - "@aws-sdk/*"
          - "@smithy/*"
      rjsf-stack:
        patterns:
          - "@rjsf/*"
      opentelemetry-stack:
        patterns:
          - "@opentelemetry/*"
          - "@vercel/otel"
      formatting-stack:
        patterns:
          - prettier
          - eslint-plugin-prettier
      markdown-stack:
        patterns:
          - markdown-*
          - remark-*
          - rehype-*
          - "@uiw/react-markdown-preview"
          - "@uiw/react-md-editor"

  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `/lib/landing` directory
    directory: '/lib/landing'
    schedule:
      interval: 'monthly'
    versioning-strategy: increase
    open-pull-requests-limit: 25
    # dependabot doesn't support YAML aliases so this is copied-and-pasted for all npm ecosystems https://github.com/dependabot/dependabot-core/issues/1582
    groups:
      react-stack:
        patterns:
          - react
          - react-dom
          - next
          - "@next/*"
          - "@mdx-js/*"
      mui-stack:
        patterns:
          - "@mui/*"
          - "@emotion/*"
          - styled-components
      eslint-stack:
        patterns:
          - eslint
          - eslint-*
          - "@eslint/*"
          - "@typescript-eslint/*"
      typescript-stack:
        patterns:
          - typescript
          - ts-node
          - "vite-tsconfig-paths"
      testing-stack:
        patterns:
          - vitest
          - "@vitest/*"
          - "@testing-library/*"
          - cypress
          - supertest
          - jsdom
      aws-sdk-stack:
        patterns:
          - "@aws-sdk/*"
          - "@smithy/*"
      rjsf-stack:
        patterns:
          - "@rjsf/*"
      opentelemetry-stack:
        patterns:
          - "@opentelemetry/*"
          - "@vercel/otel"
      formatting-stack:
        patterns:
          - prettier
          - eslint-plugin-prettier
      markdown-stack:
        patterns:
          - markdown-*
          - remark-*
          - rehype-*
          - "@uiw/react-markdown-preview"
          - "@uiw/react-md-editor"

  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `/backend` directory
    directory: '/backend'
    schedule:
      interval: 'monthly'
    versioning-strategy: increase
    open-pull-requests-limit: 25
    # dependabot doesn't support YAML aliases so this is copied-and-pasted for all npm ecosystems https://github.com/dependabot/dependabot-core/issues/1582
    groups:
      react-stack:
        patterns:
          - react
          - react-dom
          - next
          - "@next/*"
          - "@mdx-js/*"
      mui-stack:
        patterns:
          - "@mui/*"
          - "@emotion/*"
          - styled-components
      eslint-stack:
        patterns:
          - eslint
          - eslint-*
          - "@eslint/*"
          - "@typescript-eslint/*"
      typescript-stack:
        patterns:
          - typescript
          - ts-node
          - "vite-tsconfig-paths"
      testing-stack:
        patterns:
          - vitest
          - "@vitest/*"
          - "@testing-library/*"
          - cypress
          - supertest
          - jsdom
      aws-sdk-stack:
        patterns:
          - "@aws-sdk/*"
          - "@smithy/*"
      rjsf-stack:
        patterns:
          - "@rjsf/*"
      opentelemetry-stack:
        patterns:
          - "@opentelemetry/*"
          - "@vercel/otel"
      formatting-stack:
        patterns:
          - prettier
          - eslint-plugin-prettier
      markdown-stack:
        patterns:
          - markdown-*
          - remark-*
          - rehype-*
          - "@uiw/react-markdown-preview"
          - "@uiw/react-md-editor"

  # Enable version updates for Docker
  - package-ecosystem: 'docker'
    # Look for a `Dockerfile` in these directories
    directories:
      - '/'
      - '/backend'
      - '/frontend'
      - '/lib/modelscan_api'
    # Check for updates once a week
    schedule:
      interval: 'weekly'

  # Enable version updates for Docker Compose
  - package-ecosystem: 'docker-compose'
    # Look for docker-compose in these directories
    directories:
      - '/'
    # Check for updates once a week
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'helm'
    directories:
      - '/infrastructure/helm/bailo'
    schedule:
      interval: 'weekly'

  # Enable version updates for python bailo package
  - package-ecosystem: 'pip'
    # Look for a `requirements*` or `pyproject.toml` in these directories
    directories:
      - '/lib/python'
    schedule:
      interval: 'weekly'
    versioning-strategy: increase
    open-pull-requests-limit: 10

  # Enable version updates for python modelscan api
  - package-ecosystem: 'pip'
    # Look for a `requirements*` or `pyproject.toml` in these directories
    directories:
      - '/lib/modelscan_api'
    schedule:
      interval: 'weekly'
    versioning-strategy: increase
    open-pull-requests-limit: 10

  # Enable version updates for python docs
  - package-ecosystem: 'pip'
    # Look for a `requirements*` or `pyproject.toml` in these directories
    directories:
      - '/backend/docs'
    schedule:
      interval: 'weekly'
    versioning-strategy: increase
    open-pull-requests-limit: 10

  # Set update schedule for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 12
