name: bailo-dev

services:
  webhook-tester:
    networks:
      default:
      internal:
    image: tarampampam/webhook-tester:2.2.3
    command: serve --auto-create-sessions
    ports:
      - 8082:8080

  mailcrab:
    networks:
      default:
      internal:
    ports:
      - 1080:1080
      - 1025:1025
    image: marlonb/mailcrab:v1.6.2

  backend:
    ports:
      - 9229:9229
    volumes:
      - ./backend/src:/app/src
    build:
      target: dev

  frontend:
    volumes:
      - ./frontend:/app
    build:
      target: dev

  modelscan:
    volumes:
      - ./lib/modelscan_api/bailo_modelscan_api:/app/bailo_modelscan_api
    build:
      target: dev

  s3:
    networks:
      default:
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_EXTERNAL_ADDRESS=:9000
      - RUSTFS_ACCESS_KEY=s3admin
      - RUSTFS_SECRET_KEY=s3admin
      - RUSTFS_CONSOLE_ENABLE=true

networks:
  debug:
    name: ${INSTANCE_NAME}_debug
